---
galaxy_info:
  author: ivan
  description: Install lsd (modern ls replacement) command-line tool
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - cli-tools
    - terminal
    - development
    - utilities
    - ls

dependencies: []
