---
- name: "{{ role_name | default('NPM') }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name | default('NPM') }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name | default('NPM') }} | Fallback to generic installation"
  ansible.builtin.package:
    name: nodejs
    state: present
  become: true
  when: not distribution_config.stat.exists

- name: "{{ role_name | default('NPM') }} | Verify NPM installation"
  ansible.builtin.command: npm --version
  register: npm_version_check
  failed_when: false
  changed_when: false

- name: "{{ role_name | default('NPM') }} | Display NPM version"
  ansible.builtin.debug:
    msg: "NPM version: {{ npm_version_check.stdout }}"
  when: npm_version_check.rc == 0