---
galaxy_info:
  author: ivan
  description: Install lazygit - A simple terminal UI for git commands
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: ArchLinux
      versions:
        - all

dependencies: []
