---
galaxy_info:
  author: ivan
  description: Install fd (a fast alternative to find)
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - cli-tools
    - terminal
    - find
    - utilities
    - rust

dependencies: []
