---
- name: "{{ role_name | default('CLEANUP') }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name | default('CLEANUP') }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name | default('CLEANUP') }} | Distribution not supported"
  ansible.builtin.debug:
    msg: "Cleanup tasks not available for {{ ansible_distribution }}"
  when: not distribution_config.stat.exists
