---
dependencies: []

galaxy_info:
  author: LittleHaku
  description: WezTerm terminal emulator configuration
  company: none
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - terminal
    - wezterm
    - development
