---
- name: "ZOXIDE | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "ZOXIDE | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "ZOXIDE | Fallback message when no distribution config exists"
  ansible.builtin.debug:
    msg: "No specific configuration found for {{ ansible_distribution }}. Please install zoxide manually."
  when: not distribution_config.stat.exists
