---
- name: "FZF | Uninstall APT fzf"
  ansible.builtin.apt:
    name: fzf
    state: absent
  become: true

- name: "FZF | Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.fzf"
    force: yes
    update: yes
  notify: "Install FZF"

- name: "FZF | Check if fzf is already installed"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.fzf/bin/fzf"
  register: fzf_binary
