---
- name: "{{ role_name | default('DIFFTASTIC') }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name | default('DIFFTASTIC') }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name | default('DIFFTASTIC') }} | Fallback to generic package installation"
  ansible.builtin.fail:
    msg: "No distribution-specific config found for {{ ansible_distribution }}. Difftastic installation requires distribution-specific handling."
  when: not distribution_config.stat.exists
