---
galaxy_info:
  author: ivan
  description: Install ripgrep (rg) command-line search tool
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Archlinux
      versions:
        - all

dependencies: []
