---
- name: "NEOVIM | ARCHLINUX | Install Neovim via pacman"
  community.general.pacman:
    name:
      - neovim
    state: present
  become: true

- name: "NEOVIM | ARCHLINUX | Verify Neovim installation"
  ansible.builtin.command: nvim --version
  register: neovim_version
  failed_when: false
  changed_when: false

- name: "NEOVIM | ARCHLINUX | Display Neovim version"
  ansible.builtin.debug:
    msg: "Neovim version: {{ neovim_version.stdout.split('\n')[0] if neovim_version.rc == 0 else 'Installation failed' }}"

- name: "NEOVIM | ARCHLINUX | Ensure .config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: "NEOVIM | ARCHLINUX | Remove existing nvim config if it exists and is not a symlink"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: absent
  when: ansible_env.HOME + '/.config/nvim' is not link

- name: "NEOVIM | ARCHLINUX | Create symlink to neovim configuration"
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/neovim/files/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: yes
