---
- name: "{{ role_name | default('NEOVIM') }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name | default('NEOVIM') }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name | default('NEOVIM') }} | Fallback installation not configured"
  ansible.builtin.fail:
    msg: "No distribution-specific configuration found for {{ ansible_distribution }}"
  when: not distribution_config.stat.exists
